CREATE TABLE Customer (
  id VARCHAR(255) PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  paymentId VARCHAR(255) UNIQUE
);

CREATE TABLE Owner (
  id VARCHAR(255) PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  paymentDestinationId VARCHAR(255) UNIQUE
);
